"""add_settings_notifications_module

Revision ID: 1f0a3b9c2d41
Revises: 51ae47a00a54
Create Date: 2026-08-01 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0a3b9c2d41'
down_revision: Union[str, Sequence[str], None] = '51ae47a00a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_sender_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(), nullable=False),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_built_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_code'), 'email_templates', ['code'], unique=True)
    op.create_table('notification_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_webhooks_id'), 'notification_webhooks', ['id'], unique=False)
    op.create_table('notification_dispatch_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('order_confirmation', 'order_shipped', 'order_delivered', 'order_cancelled', 'return_requested', 'abandoned_checkout', 'password_reset', 'low_stock', 'admin_notification', name='notification_event_type'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'webhook', name='notification_channel'), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['webhook_id'], ['notification_webhooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_dispatch_rules_id'), 'notification_dispatch_rules', ['id'], unique=False)
    op.create_index(op.f('ix_notification_dispatch_rules_event_type'), 'notification_dispatch_rules', ['event_type'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'webhook', name='notification_channel'), nullable=False),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='dispatch_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_notification_dispatch_rules_event_type'), table_name='notification_dispatch_rules')
    op.drop_index(op.f('ix_notification_dispatch_rules_id'), table_name='notification_dispatch_rules')
    op.drop_table('notification_dispatch_rules')
    op.drop_index(op.f('ix_notification_webhooks_id'), table_name='notification_webhooks')
    op.drop_table('notification_webhooks')
    op.drop_index(op.f('ix_email_templates_code'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_table('notification_sender_config')
    sa.Enum(name='notification_event_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notification_channel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='dispatch_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
