"""add_settings_customer_accounts_module

Revision ID: 21ca3d8248db
Revises: 9091bc26b1d4
Create Date: 2026-08-01 14:01:33.755623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ca3d8248db'
down_revision: Union[str, Sequence[str], None] = '9091bc26b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_sign_in_links', sa.Boolean(), nullable=False),
    sa.Column('allow_registration', sa.Boolean(), nullable=False),
    sa.Column('require_email_verification', sa.Boolean(), nullable=False),
    sa.Column('session_duration_days', sa.Integer(), nullable=False),
    sa.Column('allow_self_returns', sa.Boolean(), nullable=False),
    sa.Column('allow_self_cancellations', sa.Boolean(), nullable=False),
    sa.Column('return_window_days', sa.Integer(), nullable=False),
    sa.Column('allow_store_credit', sa.Boolean(), nullable=False),
    sa.Column('account_domain', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_account_settings')
    # ### end Alembic commands ###
