"""add_settings_metafields_module

Revision ID: 3b8d2c4e5f01
Revises: 2a7c5e8b3f62
Create Date: 2026-08-01 19:31:01.476644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8d2c4e5f01'
down_revision: Union[str, Sequence[str], None] = '2a7c5e8b3f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metafield_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_list', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storefront_api_access', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.Enum('all', 'categories', name='metafield_scope'), nullable=False),
    sa.Column('category_ids', sa.JSON(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'key', name='uq_metafield_definitions_resource_key')
    )
    op.create_index(op.f('ix_metafield_definitions_id'), 'metafield_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_metafield_definitions_resource_type'), 'metafield_definitions', ['resource_type'], unique=False)
    op.create_table('metafield_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('owner_resource_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['metafield_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metafield_values_definition_id'), 'metafield_values', ['definition_id'], unique=False)
    op.create_index(op.f('ix_metafield_values_id'), 'metafield_values', ['id'], unique=False)
    op.create_index(op.f('ix_metafield_values_owner_id'), 'metafield_values', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metafield_values_owner_id'), table_name='metafield_values')
    op.drop_index(op.f('ix_metafield_values_id'), table_name='metafield_values')
    op.drop_index(op.f('ix_metafield_values_definition_id'), table_name='metafield_values')
    op.drop_table('metafield_values')
    op.drop_index(op.f('ix_metafield_definitions_resource_type'), table_name='metafield_definitions')
    op.drop_index(op.f('ix_metafield_definitions_id'), table_name='metafield_definitions')
    op.drop_table('metafield_definitions')
    # ### end Alembic commands ###
