"""sync all current modules: customers, orders, catalog, settings

Revision ID: 413b2adab39d
Revises: 4bcff04ea506
Create Date: 2026-07-30 17:01:50.819537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '413b2adab39d'
down_revision: Union[str, Sequence[str], None] = '4bcff04ea506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_retention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_month', sa.String(length=7), nullable=False),
    sa.Column('months_since', sa.Integer(), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('active_customers', sa.Integer(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cohort_retention_cohort_month', 'cohort_retention', ['cohort_month'], unique=False)
    op.create_index(op.f('ix_cohort_retention_id'), 'cohort_retention', ['id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('channels', sa.Text(), nullable=True),
    sa.Column('theme_template', sa.String(), nullable=False),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=160), nullable=True),
    sa.Column('url_handle', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_handle')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index('ix_collections_url_handle', 'collections', ['url_handle'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_addresses_customer_id', 'customer_addresses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=False)
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discounts', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sales_reversals', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_charges', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('return_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('orders_fulfilled', sa.Integer(), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('sessions_desktop', sa.Integer(), nullable=False),
    sa.Column('sessions_mobile', sa.Integer(), nullable=False),
    sa.Column('sessions_tablet', sa.Integer(), nullable=False),
    sa.Column('added_to_cart', sa.Integer(), nullable=False),
    sa.Column('reached_checkout', sa.Integer(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('returning_customer_rate', sa.Float(), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.Column('returning_customers', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('landing_page', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('social_referrer', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_snapshots_date', 'daily_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_daily_snapshots_id'), 'daily_snapshots', ['id'], unique=False)
    op.create_index('ix_daily_snapshots_type', 'daily_snapshots', ['metric_type'], unique=False)
    op.create_table('explorations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_config', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explorations_id'), 'explorations', ['id'], unique=False)
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('initial_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('enabled', 'disabled', 'expired', name='gift_card_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_gift_cards_code', 'gift_cards', ['code'], unique=False)
    op.create_index(op.f('ix_gift_cards_id'), 'gift_cards', ['id'], unique=False)
    op.create_index('ix_gift_cards_status', 'gift_cards', ['status'], unique=False)
    op.create_table('live_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('visitor_city', sa.String(), nullable=True),
    sa.Column('visitor_country', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_activities_created_at', 'live_activities', ['created_at'], unique=False)
    op.create_index('ix_live_activities_event_type', 'live_activities', ['event_type'], unique=False)
    op.create_index(op.f('ix_live_activities_id'), 'live_activities', ['id'], unique=False)
    op.create_table('live_visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('visitor_ip', sa.String(), nullable=True),
    sa.Column('visitor_country', sa.String(), nullable=True),
    sa.Column('visitor_region', sa.String(), nullable=True),
    sa.Column('visitor_city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('current_page', sa.String(), nullable=True),
    sa.Column('landing_page', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('has_cart', sa.Boolean(), nullable=False),
    sa.Column('cart_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_checkout', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_live_visitors_id'), 'live_visitors', ['id'], unique=False)
    op.create_index('ix_live_visitors_last_active', 'live_visitors', ['last_active_at'], unique=False)
    op.create_index('ix_live_visitors_session_id', 'live_visitors', ['session_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_category', 'reports', ['category'], unique=False)
    op.create_index('ix_reports_created_by', 'reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('destination_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'received', 'cancelled', name='purchase_order_status'), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('note_to_supplier', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_table('abandoned_checkout_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('variant_title', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['abandoned_checkouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('location_id_ref', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('ship_to_address', sa.Boolean(), nullable=False),
    sa.Column('order_submission', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_locations_company_id', 'company_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_locations_id'), 'company_locations', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('bin_name', sa.String(), nullable=True),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('committed', sa.Integer(), nullable=False),
    sa.Column('unavailable', sa.Integer(), nullable=False),
    sa.Column('incoming', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index('ix_inventory_items_location_id', 'inventory_items', ['location_id'], unique=False)
    op.create_index('ix_inventory_items_variant_id', 'inventory_items', ['variant_id'], unique=False)
    op.create_table('order_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_audit_logs_id'), 'order_audit_logs', ['id'], unique=False)
    op.create_table('order_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_notes_id'), 'order_notes', ['id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_items_po_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_location_id', sa.Integer(), nullable=False),
    sa.Column('destination_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'received', name='transfer_status'), nullable=False),
    sa.Column('reference_name', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('linked_purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['linked_purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    op.create_index('ix_transfers_status', 'transfers', ['status'], unique=False)
    op.add_column('abandoned_checkouts', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PKR'))
    op.add_column('abandoned_checkouts', sa.Column('recovery_token', sa.String(), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('recovery_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('recovery_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('abandoned_checkouts', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('browser_info', sa.String(), nullable=True))
    op.add_column('abandoned_checkouts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'abandoned_checkouts', ['recovery_token'])
    op.create_foreign_key(None, 'abandoned_checkouts', 'customers', ['customer_id'], ['id'])
    op.add_column('companies', sa.Column('company_id_ref', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('main_contact_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('billing_address_same_as_shipping', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('companies', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('tax_settings', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('note', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['company_id_ref'])
    op.create_foreign_key(None, 'companies', 'customers', ['main_contact_id'], ['id'])
    op.add_column('customers', sa.Column('phone_country_code', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('first_order_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('tax_settings', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('default_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'customer_addresses', ['default_address_id'], ['id'])
    op.add_column('draft_order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('draft_order_items', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('draft_order_items', sa.Column('variant_title', sa.String(), nullable=True))
    op.add_column('draft_order_items', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('draft_order_items', sa.Column('requires_shipping', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('draft_order_items', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('draft_orders', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('draft_orders', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('draft_orders', sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('draft_orders', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('draft_orders', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PKR'))
    op.add_column('draft_orders', sa.Column('market', sa.String(), nullable=True))
    op.add_column('draft_orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('draft_orders', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('draft_orders', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('variant_title', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('order_items', sa.Column('requires_shipping', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('order_items', sa.Column('is_gift_card', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('order_items', sa.Column('restocked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PKR'))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('tracking_company', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('customer_note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('internal_note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('conversion_summary', sa.Text(), nullable=True))
    op.add_column('product_images', sa.Column('focal_point_x', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('product_images', sa.Column('focal_point_y', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('product_variants', sa.Column('cost_per_item', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_variants', sa.Column('barcode', sa.String(), nullable=True))
    op.execute("CREATE TYPE weight_unit AS ENUM ('kg', 'g', 'lb', 'oz')")
    op.add_column('product_variants', sa.Column('weight_unit', sa.Enum('kg', 'g', 'lb', 'oz', name='weight_unit', create_type=False), nullable=False, server_default='kg'))
    op.add_column('product_variants', sa.Column('inventory_tracked', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('product_variants', sa.Column('continue_selling_out_of_stock', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('channels', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('theme_template', sa.String(), nullable=False, server_default='default'))
    op.add_column('products', sa.Column('seo_title', sa.String(length=70), nullable=True))
    op.add_column('products', sa.Column('seo_description', sa.String(length=160), nullable=True))
    op.add_column('products', sa.Column('url_handle', sa.String(), nullable=True))
    op.execute("CREATE TYPE product_status AS ENUM ('active', 'draft', 'archived')")
    op.execute("ALTER TABLE products ALTER COLUMN status TYPE product_status USING status::text::product_status")
    op.execute("CREATE TYPE product_category AS ENUM ('belts', 'wallets', 'bags', 'jackets', 'shoes', 'accessories', 'other')")
    op.execute("ALTER TABLE products ALTER COLUMN category TYPE product_category USING category::text::product_category")
    op.alter_column('products', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_products_url_handle', 'products', ['url_handle'], unique=False)
    op.create_unique_constraint(None, 'products', ['url_handle'])
    op.drop_column('products', 'channel')
    op.add_column('segments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('segments', sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'is_system')
    op.drop_column('segments', 'description')
    op.add_column('products', sa.Column('channel', postgresql.ENUM('online_store', 'whatsapp', 'facebook_instagram', 'agentic', 'pos', name='saleschannel'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('ix_products_url_handle', table_name='products')
    op.alter_column('products', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("ALTER TABLE products ALTER COLUMN category TYPE productcategory USING category::text::productcategory")
    op.execute("ALTER TABLE products ALTER COLUMN status TYPE productstatus USING status::text::productstatus")
    op.execute("DROP TYPE IF EXISTS product_status")
    op.execute("DROP TYPE IF EXISTS product_category")
    op.drop_column('products', 'url_handle')
    op.drop_column('products', 'seo_description')
    op.drop_column('products', 'seo_title')
    op.drop_column('products', 'theme_template')
    op.drop_column('products', 'channels')
    op.drop_column('products', 'product_type')
    op.drop_column('product_variants', 'continue_selling_out_of_stock')
    op.drop_column('product_variants', 'inventory_tracked')
    op.drop_column('product_variants', 'weight_unit')
    op.execute("DROP TYPE IF EXISTS weight_unit")
    op.drop_column('product_variants', 'barcode')
    op.drop_column('product_variants', 'cost_per_item')
    op.drop_column('product_images', 'focal_point_y')
    op.drop_column('product_images', 'focal_point_x')
    op.drop_column('orders', 'conversion_summary')
    op.drop_column('orders', 'risk_level')
    op.drop_column('orders', 'internal_note')
    op.drop_column('orders', 'customer_note')
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'tracking_company')
    op.drop_column('orders', 'paid_amount')
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'shipping_cost')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'closed_at')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('order_items', 'restocked')
    op.drop_column('order_items', 'is_gift_card')
    op.drop_column('order_items', 'requires_shipping')
    op.drop_column('order_items', 'total_price')
    op.drop_column('order_items', 'variant_title')
    op.drop_column('order_items', 'variant_id')
    op.drop_column('draft_orders', 'tags')
    op.drop_column('draft_orders', 'billing_address')
    op.drop_column('draft_orders', 'shipping_address')
    op.drop_column('draft_orders', 'market')
    op.drop_column('draft_orders', 'currency')
    op.drop_column('draft_orders', 'tax')
    op.drop_column('draft_orders', 'shipping_cost')
    op.drop_column('draft_orders', 'customer_phone')
    op.drop_column('draft_orders', 'customer_email')
    op.drop_column('draft_order_items', 'is_custom')
    op.drop_column('draft_order_items', 'requires_shipping')
    op.drop_column('draft_order_items', 'total_price')
    op.drop_column('draft_order_items', 'variant_title')
    op.drop_column('draft_order_items', 'sku')
    op.drop_column('draft_order_items', 'variant_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'default_address_id')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'tags')
    op.drop_column('customers', 'tax_settings')
    op.drop_column('customers', 'last_order_date')
    op.drop_column('customers', 'first_order_date')
    op.drop_column('customers', 'phone_country_code')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'note')
    op.drop_column('companies', 'tax_settings')
    op.drop_column('companies', 'tax_id')
    op.drop_column('companies', 'billing_address')
    op.drop_column('companies', 'billing_address_same_as_shipping')
    op.drop_column('companies', 'main_contact_id')
    op.drop_column('companies', 'company_id_ref')
    op.drop_constraint(None, 'abandoned_checkouts', type_='foreignkey')
    op.drop_constraint(None, 'abandoned_checkouts', type_='unique')
    op.drop_column('abandoned_checkouts', 'updated_at')
    op.drop_column('abandoned_checkouts', 'browser_info')
    op.drop_column('abandoned_checkouts', 'ip_address')
    op.drop_column('abandoned_checkouts', 'shipping_address')
    op.drop_column('abandoned_checkouts', 'recovery_attempts')
    op.drop_column('abandoned_checkouts', 'recovered_at')
    op.drop_column('abandoned_checkouts', 'recovery_email_sent_at')
    op.drop_column('abandoned_checkouts', 'recovery_token')
    op.drop_column('abandoned_checkouts', 'currency')
    op.drop_column('abandoned_checkouts', 'customer_phone')
    op.drop_column('abandoned_checkouts', 'customer_id')
    op.drop_index('ix_transfers_status', table_name='transfers')
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_index('ix_po_items_po_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_order_notes_id'), table_name='order_notes')
    op.drop_table('order_notes')
    op.drop_index(op.f('ix_order_audit_logs_id'), table_name='order_audit_logs')
    op.drop_table('order_audit_logs')
    op.drop_index('ix_inventory_items_variant_id', table_name='inventory_items')
    op.drop_index('ix_inventory_items_location_id', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_company_locations_id'), table_name='company_locations')
    op.drop_index('ix_company_locations_company_id', table_name='company_locations')
    op.drop_table('company_locations')
    op.drop_table('abandoned_checkout_items')
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('ix_reports_created_by', table_name='reports')
    op.drop_index('ix_reports_category', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_live_visitors_session_id', table_name='live_visitors')
    op.drop_index('ix_live_visitors_last_active', table_name='live_visitors')
    op.drop_index(op.f('ix_live_visitors_id'), table_name='live_visitors')
    op.drop_table('live_visitors')
    op.drop_index(op.f('ix_live_activities_id'), table_name='live_activities')
    op.drop_index('ix_live_activities_event_type', table_name='live_activities')
    op.drop_index('ix_live_activities_created_at', table_name='live_activities')
    op.drop_table('live_activities')
    op.drop_index('ix_gift_cards_status', table_name='gift_cards')
    op.drop_index(op.f('ix_gift_cards_id'), table_name='gift_cards')
    op.drop_index('ix_gift_cards_code', table_name='gift_cards')
    op.drop_table('gift_cards')
    op.drop_index(op.f('ix_explorations_id'), table_name='explorations')
    op.drop_table('explorations')
    op.drop_index('ix_daily_snapshots_type', table_name='daily_snapshots')
    op.drop_index(op.f('ix_daily_snapshots_id'), table_name='daily_snapshots')
    op.drop_index('ix_daily_snapshots_date', table_name='daily_snapshots')
    op.drop_table('daily_snapshots')
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_customer_id', table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index('ix_collections_url_handle', table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_cohort_retention_id'), table_name='cohort_retention')
    op.drop_index('ix_cohort_retention_cohort_month', table_name='cohort_retention')
    op.drop_table('cohort_retention')
    # ### end Alembic commands ###
