"""add_companies_segments_customer_overhaul

Revision ID: 4bcff04ea506
Revises: 94ba95f3ae67
Create Date: 2026-07-27 19:30:13.362578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcff04ea506'
down_revision: Union[str, Sequence[str], None] = '94ba95f3ae67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('custom_pricing_tier', sa.String(), nullable=True),
    sa.Column('net_payment_terms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percentage_of_customers', sa.Float(), nullable=False),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('query_definition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_index('ix_segments_name', 'segments', ['name'], unique=False)
    op.create_table('customer_company',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'company_id')
    )
    op.create_table('customer_segment',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'segment_id')
    )
    op.add_column('customers', sa.Column('location', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('customer_language', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('email_subscription', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('customers', sa.Column('sms_subscription', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('customers', sa.Column('whatsapp_subscription', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('customers', sa.Column('total_orders', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('customers', sa.Column('amount_spent', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('customers', sa.Column('tax_exempt', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('customers', sa.Column('deletable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('customers', sa.Column('mergeable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_last_name', 'customers', ['last_name'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_unique_constraint(None, 'customers', ['email'])
    op.drop_column('customers', 'default_address')
    op.drop_column('customers', 'note')
    op.drop_column('customers', 'tags')
    op.drop_column('customers', 'orders_count')
    op.drop_column('customers', 'total_spent')
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('total_spent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('orders_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('default_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_last_name', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.drop_column('customers', 'mergeable')
    op.drop_column('customers', 'deletable')
    op.drop_column('customers', 'tax_exempt')
    op.drop_column('customers', 'amount_spent')
    op.drop_column('customers', 'total_orders')
    op.drop_column('customers', 'whatsapp_subscription')
    op.drop_column('customers', 'sms_subscription')
    op.drop_column('customers', 'email_subscription')
    op.drop_column('customers', 'customer_language')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'location')
    op.drop_table('customer_segment')
    op.drop_table('customer_company')
    op.drop_index('ix_segments_name', table_name='segments')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
