"""add_settings_customer_events_module

Revision ID: 51ae47a00a54
Revises: 41d5ddc0f3da
Create Date: 2026-08-01 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ae47a00a54'
down_revision: Union[str, Sequence[str], None] = '41d5ddc0f3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_pixels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('facebook', 'instagram', 'google_analytics', 'microsoft_clarity', 'judge_me', 'tiktok', 'pinterest', 'snapchat', 'custom', 'other', name='pixel_provider'), nullable=False),
    sa.Column('kind', sa.Enum('web', 'server', name='pixel_kind'), nullable=False),
    sa.Column('pixel_id', sa.String(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('placement', sa.Enum('head', 'body_start', 'body_end', 'checkout', name='pixel_placement'), nullable=False),
    sa.Column('data_health', sa.Enum('always_on', 'optimized', name='pixel_data_health'), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('app_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_pixels_id'), 'tracking_pixels', ['id'], unique=False)
    op.create_table('pixel_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pixel_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pixel_event_logs_id'), 'pixel_event_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pixel_event_logs_id'), table_name='pixel_event_logs')
    op.drop_table('pixel_event_logs')
    op.drop_index(op.f('ix_tracking_pixels_id'), table_name='tracking_pixels')
    op.drop_table('tracking_pixels')
    sa.Enum(name='pixel_provider').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='pixel_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='pixel_placement').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='pixel_data_health').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
