"""create_orders_tables

Revision ID: 6393e93a9154
Revises: 4d5e969eb07d
Create Date: 2026-07-27 18:45:43.528140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6393e93a9154'
down_revision: Union[str, Sequence[str], None] = '4d5e969eb07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abandoned_checkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_reference', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('recovery_status', sa.Enum('not_sent', 'email_sent', 'recovered', 'lost', name='recoverystatus'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_checkouts_checkout_reference'), 'abandoned_checkouts', ['checkout_reference'], unique=True)
    op.create_index(op.f('ix_abandoned_checkouts_id'), 'abandoned_checkouts', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('default_address', sa.String(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('draft_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'invoice_sent', 'completed', 'cancelled', name='draftorderstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_orders_draft_number'), 'draft_orders', ['draft_number'], unique=True)
    op.create_index(op.f('ix_draft_orders_id'), 'draft_orders', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('fulfill_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'pending', 'voided', 'refunded', 'partially_paid', name='paymentstatus'), nullable=False),
    sa.Column('fulfillment_status', sa.Enum('fulfilled', 'unfulfilled', 'partial', 'scheduled', name='fulfillmentstatus'), nullable=False),
    sa.Column('delivery_status', sa.Enum('pending', 'in_transit', 'out_for_delivery', 'delivered', 'failed', 'returned', name='deliverystatus'), nullable=False),
    sa.Column('delivery_method', sa.Enum('standard', 'express', 'pickup', name='deliverymethod'), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('return_status', sa.Enum('none', 'requested', 'approved', 'received', 'refunded', name='returnstatus'), nullable=False),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('label_status', sa.Enum('not_generated', 'generated', 'printed', name='labelstatus'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('draft_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['draft_order_id'], ['draft_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('draft_order_items')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_draft_orders_id'), table_name='draft_orders')
    op.drop_index(op.f('ix_draft_orders_draft_number'), table_name='draft_orders')
    op.drop_table('draft_orders')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_abandoned_checkouts_id'), table_name='abandoned_checkouts')
    op.drop_index(op.f('ix_abandoned_checkouts_checkout_reference'), table_name='abandoned_checkouts')
    op.drop_table('abandoned_checkouts')
    # ### end Alembic commands ###
