"""create_missing_tables_growth_discounts_content_markets

Revision ID: 66d0096c48fa
Revises: d84147f93891
Create Date: 2026-07-30 18:19:44.969216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d0096c48fa'
down_revision: Union[str, Sequence[str], None] = 'd84147f93891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('roas', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cpa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('aov', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('orders_from_new_customers', sa.Integer(), nullable=False),
    sa.Column('orders_from_returning_customers', sa.Integer(), nullable=False),
    sa.Column('referring_category', sa.String(), nullable=True),
    sa.Column('referring_url', sa.String(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attribution_channel', 'attribution', ['channel'], unique=False)
    op.create_index('ix_attribution_created_at', 'attribution', ['created_at'], unique=False)
    op.create_index(op.f('ix_attribution_id'), 'attribution', ['id'], unique=False)
    op.create_index('ix_attribution_type', 'attribution', ['type'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('blog', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('visibility', sa.Enum('visible', 'hidden', name='blog_visibility'), nullable=False),
    sa.Column('featured_image_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('seo_title', sa.String(), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('template_suffix', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_index('ix_blog_posts_author', 'blog_posts', ['author'], unique=False)
    op.create_index('ix_blog_posts_blog', 'blog_posts', ['blog'], unique=False)
    op.create_index('ix_blog_posts_handle', 'blog_posts', ['handle'], unique=False)
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index('ix_blog_posts_published_at', 'blog_posts', ['published_at'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'draft', 'completed', 'paused', name='campaign_status'), nullable=False),
    sa.Column('unassigned_activities_count', sa.Integer(), nullable=False),
    sa.Column('target_metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_created_at', 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'scheduled', 'disabled', name='discount_status'), nullable=False),
    sa.Column('method', sa.Enum('code', 'automatic', name='discount_method'), nullable=False),
    sa.Column('eligibility', sa.Enum('all_customers', 'specific_customers', 'specific_segments', name='discount_eligibility'), nullable=False),
    sa.Column('type', sa.Enum('percentage', 'fixed_amount', 'free_shipping', 'buy_x_get_y', name='discount_type'), nullable=False),
    sa.Column('combinations', sa.Text(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_discounts_code', 'discounts', ['code'], unique=False)
    op.create_index('ix_discounts_created_at', 'discounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)
    op.create_index('ix_discounts_status', 'discounts', ['status'], unique=False)
    op.create_index('ix_discounts_type', 'discounts', ['type'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('references_count', sa.Integer(), nullable=False),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('focal_point_x', sa.Float(), nullable=True),
    sa.Column('focal_point_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_created_at', 'files', ['created_at'], unique=False)
    op.create_index('ix_files_filename', 'files', ['filename'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'draft', name='market_status'), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('includes', sa.Text(), nullable=True),
    sa.Column('customizations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_markets_country_code', 'markets', ['country_code'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_index('ix_markets_status', 'markets', ['status'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_index('ix_menus_handle', 'menus', ['handle'], unique=False)
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_table('metaobject_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('available_on_storefront', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_key')
    )
    op.create_index(op.f('ix_metaobject_definitions_id'), 'metaobject_definitions', ['id'], unique=False)
    op.create_index('ix_metaobject_definitions_type_key', 'metaobject_definitions', ['type_key'], unique=False)
    op.create_table('rollouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'completed', name='rollout_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollouts_id'), 'rollouts', ['id'], unique=False)
    op.create_index('ix_rollouts_status', 'rollouts', ['status'], unique=False)
    op.create_table('url_redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_path', sa.String(), nullable=False),
    sa.Column('to_path', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('home', 'collection', 'product', 'page', 'blog_post', 'custom', name='redirect_target_type'), nullable=True),
    sa.Column('redirect_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_redirects_from_path', 'url_redirects', ['from_path'], unique=False)
    op.create_index(op.f('ix_url_redirects_id'), 'url_redirects', ['id'], unique=False)
    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'spam', name='blog_comment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comments_id'), 'blog_comments', ['id'], unique=False)
    op.create_index('ix_blog_comments_post_id', 'blog_comments', ['post_id'], unique=False)
    op.create_index('ix_blog_comments_status', 'blog_comments', ['status'], unique=False)
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'draft', name='catalog_status'), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('price_adjustment_direction', sa.Enum('increase', 'decrease', name='price_adjustment_direction'), nullable=False),
    sa.Column('price_adjustment_value', sa.Float(), nullable=False),
    sa.Column('include_compare_at', sa.Boolean(), nullable=False),
    sa.Column('auto_include_new_products', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_id'), 'catalogs', ['id'], unique=False)
    op.create_index('ix_catalogs_market_id', 'catalogs', ['market_id'], unique=False)
    op.create_index('ix_catalogs_status', 'catalogs', ['status'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('target', sa.Enum('same_window', 'new_window', name='menu_target'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index('ix_menu_items_menu_id', 'menu_items', ['menu_id'], unique=False)
    op.create_index('ix_menu_items_parent_id', 'menu_items', ['parent_id'], unique=False)
    op.create_table('metaobject_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'draft', name='metaobject_status'), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('references_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['metaobject_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metaobject_entries_created_at', 'metaobject_entries', ['created_at'], unique=False)
    op.create_index('ix_metaobject_entries_definition_id', 'metaobject_entries', ['definition_id'], unique=False)
    op.create_index(op.f('ix_metaobject_entries_id'), 'metaobject_entries', ['id'], unique=False)
    op.create_index('ix_metaobject_entries_status', 'metaobject_entries', ['status'], unique=False)
    op.create_table('rollout_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rollout_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('online_store_theme', 'checkout_and_accounts', name='change_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'applied', 'reverted', name='rollout_change_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rollout_id'], ['rollouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollout_changes_id'), 'rollout_changes', ['id'], unique=False)
    op.create_index('ix_rollout_changes_rollout_id', 'rollout_changes', ['rollout_id'], unique=False)
    op.create_table('catalog_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_products_catalog_id', 'catalog_products', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_catalog_products_id'), 'catalog_products', ['id'], unique=False)
    op.create_index('ix_catalog_products_product_id', 'catalog_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_products_product_id', table_name='catalog_products')
    op.drop_index(op.f('ix_catalog_products_id'), table_name='catalog_products')
    op.drop_index('ix_catalog_products_catalog_id', table_name='catalog_products')
    op.drop_table('catalog_products')
    op.drop_index('ix_rollout_changes_rollout_id', table_name='rollout_changes')
    op.drop_index(op.f('ix_rollout_changes_id'), table_name='rollout_changes')
    op.drop_table('rollout_changes')
    op.drop_index('ix_metaobject_entries_status', table_name='metaobject_entries')
    op.drop_index(op.f('ix_metaobject_entries_id'), table_name='metaobject_entries')
    op.drop_index('ix_metaobject_entries_definition_id', table_name='metaobject_entries')
    op.drop_index('ix_metaobject_entries_created_at', table_name='metaobject_entries')
    op.drop_table('metaobject_entries')
    op.drop_index('ix_menu_items_parent_id', table_name='menu_items')
    op.drop_index('ix_menu_items_menu_id', table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_catalogs_status', table_name='catalogs')
    op.drop_index('ix_catalogs_market_id', table_name='catalogs')
    op.drop_index(op.f('ix_catalogs_id'), table_name='catalogs')
    op.drop_table('catalogs')
    op.drop_index('ix_blog_comments_status', table_name='blog_comments')
    op.drop_index('ix_blog_comments_post_id', table_name='blog_comments')
    op.drop_index(op.f('ix_blog_comments_id'), table_name='blog_comments')
    op.drop_table('blog_comments')
    op.drop_index(op.f('ix_url_redirects_id'), table_name='url_redirects')
    op.drop_index('ix_url_redirects_from_path', table_name='url_redirects')
    op.drop_table('url_redirects')
    op.drop_index('ix_rollouts_status', table_name='rollouts')
    op.drop_index(op.f('ix_rollouts_id'), table_name='rollouts')
    op.drop_table('rollouts')
    op.drop_index('ix_metaobject_definitions_type_key', table_name='metaobject_definitions')
    op.drop_index(op.f('ix_metaobject_definitions_id'), table_name='metaobject_definitions')
    op.drop_table('metaobject_definitions')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_index('ix_menus_handle', table_name='menus')
    op.drop_table('menus')
    op.drop_index('ix_markets_status', table_name='markets')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index('ix_markets_country_code', table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index('ix_files_filename', table_name='files')
    op.drop_index('ix_files_created_at', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_discounts_type', table_name='discounts')
    op.drop_index('ix_discounts_status', table_name='discounts')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_index('ix_discounts_created_at', table_name='discounts')
    op.drop_index('ix_discounts_code', table_name='discounts')
    op.drop_table('discounts')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_created_at', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_blog_posts_published_at', table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_handle', table_name='blog_posts')
    op.drop_index('ix_blog_posts_blog', table_name='blog_posts')
    op.drop_index('ix_blog_posts_author', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index('ix_attribution_type', table_name='attribution')
    op.drop_index(op.f('ix_attribution_id'), table_name='attribution')
    op.drop_index('ix_attribution_created_at', table_name='attribution')
    op.drop_index('ix_attribution_channel', table_name='attribution')
    op.drop_table('attribution')
    # ### end Alembic commands ###
