"""add_welcome_discount_system

Revision ID: 744b5148a114
Revises: a3b9c4d5e6f7
Create Date: 2026-08-03 18:12:49.622545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744b5148a114'
down_revision: Union[str, Sequence[str], None] = 'a3b9c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('welcome_discount_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welcome_discount_logs_id'), 'welcome_discount_logs', ['id'], unique=False)
    op.create_index('ix_welcome_discount_logs_ip_address', 'welcome_discount_logs', ['ip_address'], unique=False)
    op.create_index('ix_welcome_discount_logs_user_email', 'welcome_discount_logs', ['user_email'], unique=False)
    op.create_table('welcome_discount_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welcome_discount_settings_id'), 'welcome_discount_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_welcome_discount_settings_id'), table_name='welcome_discount_settings')
    op.drop_table('welcome_discount_settings')
    op.drop_index('ix_welcome_discount_logs_user_email', table_name='welcome_discount_logs')
    op.drop_index('ix_welcome_discount_logs_ip_address', table_name='welcome_discount_logs')
    op.drop_index(op.f('ix_welcome_discount_logs_id'), table_name='welcome_discount_logs')
    op.drop_table('welcome_discount_logs')
    # ### end Alembic commands ###
