"""add_store_header_scripts

Revision ID: 95ff2b7210ab
Revises: 744b5148a114
Create Date: 2026-08-03 18:40:26.325233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ff2b7210ab'
down_revision: Union[str, Sequence[str], None] = '744b5148a114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_header_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('header_scripts', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_store_header_scripts_id'), 'store_header_scripts', ['id'], unique=False)
    op.create_index('ix_store_header_scripts_user_id', 'store_header_scripts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_store_header_scripts_user_id', table_name='store_header_scripts')
    op.drop_index(op.f('ix_store_header_scripts_id'), table_name='store_header_scripts')
    op.drop_table('store_header_scripts')
    # ### end Alembic commands ###
