"""sync all current modules: customers, orders, catalog, settings

Revision ID: d84147f93891
Revises: 413b2adab39d
Create Date: 2026-07-30 17:47:28.866848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84147f93891'
down_revision: Union[str, Sequence[str], None] = '413b2adab39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.Enum('individual', 'company', 'non_profit', name='businesstype'), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('residential_address', sa.String(), nullable=True),
    sa.Column('appartment', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('square_logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('slogan', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('social_links', sa.String(), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('store_phone', sa.String(), nullable=True),
    sa.Column('comapny_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('appartment', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('backup_region', sa.String(), nullable=False),
    sa.Column('default_weight_unit', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('unit_system', sa.String(), nullable=False),
    sa.Column('order_id_prefix', sa.String(), nullable=False),
    sa.Column('order_id_sufix', sa.String(), nullable=True),
    sa.Column('fulfillment_policy', sa.Enum('auto_fulfill_all', 'auto_fulfill_giftCard_only', 'manual', name='fulfillmentpolicy'), nullable=False),
    sa.Column('auto_archive_on_fulfillment', sa.Boolean(), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_settings')
    op.drop_table('store_brand')
    op.drop_table('business_entity')
    # ### end Alembic commands ###
