"""add_settings_apps_module

Revision ID: dc6c80be1d5c
Revises: cec326ae01b6
Create Date: 2026-08-01 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6c80be1d5c'
down_revision: Union[str, Sequence[str], None] = 'cec326ae01b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_code', sa.String(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('shipping', 'tracking', 'analytics', 'marketing', 'reviews', 'email', 'sms', 'payments', 'other', name='app_category'), nullable=False),
    sa.Column('status', sa.Enum('installed', 'active', 'inactive', name='app_status'), nullable=False),
    sa.Column('api_credentials', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_code')
    )
    op.create_index(op.f('ix_store_integrations_id'), 'store_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_store_integrations_app_code'), 'store_integrations', ['app_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_integrations_app_code'), table_name='store_integrations')
    op.drop_index(op.f('ix_store_integrations_id'), table_name='store_integrations')
    op.drop_table('store_integrations')
    sa.Enum(name='app_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='app_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
