"""add_settings_languages_module

Revision ID: 2a7c5e8b3f62
Revises: 1f0a3b9c2d41
Create Date: 2026-08-01 19:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7c5e8b3f62'
down_revision: Union[str, Sequence[str], None] = '1f0a3b9c2d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('language_name', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('published', 'unpublished', name='language_status'), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_languages_id'), 'store_languages', ['id'], unique=False)
    op.create_index(op.f('ix_store_languages_language_code'), 'store_languages', ['language_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_languages_language_code'), table_name='store_languages')
    op.drop_index(op.f('ix_store_languages_id'), table_name='store_languages')
    op.drop_table('store_languages')
    sa.Enum(name='language_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
