"""add_settings_sales_channels_module

Revision ID: 41d5ddc0f3da
Revises: dc6c80be1d5c
Create Date: 2026-08-01 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d5ddc0f3da'
down_revision: Union[str, Sequence[str], None] = 'dc6c80be1d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'not_connected', name='channel_status'), nullable=False),
    sa.Column('auth_tokens', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_code')
    )
    op.create_index(op.f('ix_sales_channels_id'), 'sales_channels', ['id'], unique=False)
    op.create_index(op.f('ix_sales_channels_channel_code'), 'sales_channels', ['channel_code'], unique=True)
    op.create_table('channel_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', name='webhook_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('processed_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_webhook_events_id'), 'channel_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_channel_webhook_events_channel_code'), 'channel_webhook_events', ['channel_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_webhook_events_channel_code'), table_name='channel_webhook_events')
    op.drop_index(op.f('ix_channel_webhook_events_id'), table_name='channel_webhook_events')
    op.drop_table('channel_webhook_events')
    op.drop_index(op.f('ix_sales_channels_channel_code'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_id'), table_name='sales_channels')
    op.drop_table('sales_channels')
    sa.Enum(name='channel_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='webhook_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
