"""add_settings_checkout_module

Revision ID: 9091bc26b1d4
Revises: 61e9aa6a1fec
Create Date: 2026-08-01 13:54:11.690588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9091bc26b1d4'
down_revision: Union[str, Sequence[str], None] = '61e9aa6a1fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_method', sa.Enum('phone_or_email', 'email', name='checkout_contact_method'), nullable=False),
    sa.Column('show_order_tracking_link', sa.Boolean(), nullable=False),
    sa.Column('require_login', sa.Boolean(), nullable=False),
    sa.Column('full_name_field', sa.Enum('don_t_include', 'optional', 'required', name='form_field_requirement'), nullable=False),
    sa.Column('company_name_field', sa.Enum('don_t_include', 'optional', 'required', name='form_field_requirement'), nullable=False),
    sa.Column('address_line2_field', sa.Enum('don_t_include', 'optional', 'required', name='form_field_requirement'), nullable=False),
    sa.Column('shipping_phone_field', sa.Enum('don_t_include', 'optional', 'required', name='form_field_requirement'), nullable=False),
    sa.Column('marketing_email_optin', sa.Enum('checkout_only', 'signin_only', 'checkout_and_signin', 'don_t_show', name='email_optin_option'), nullable=False),
    sa.Column('marketing_sms_optin', sa.Enum('don_t_show', 'checkout_only', name='sms_optin_option'), nullable=False),
    sa.Column('show_tipping', sa.Boolean(), nullable=False),
    sa.Column('checkout_language', sa.String(), nullable=False),
    sa.Column('billing_address_rule', sa.Enum('allow_different', 'require_match', name='billing_address_rule'), nullable=False),
    sa.Column('validate_shipping_address', sa.Boolean(), nullable=False),
    sa.Column('use_shipping_as_billing_default', sa.Boolean(), nullable=False),
    sa.Column('enable_cart_limit', sa.Boolean(), nullable=False),
    sa.Column('cart_item_limit', sa.Integer(), nullable=False),
    sa.Column('checkout_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_configs_id'), 'checkout_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkout_configs_id'), table_name='checkout_configs')
    op.drop_table('checkout_configs')
    # ### end Alembic commands ###
