"""add_settings_shipping_and_delivery_module

Revision ID: e4ae8f9bf31e
Revises: 21ca3d8248db
Create Date: 2026-08-01 14:15:57.483002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ae8f9bf31e'
down_revision: Union[str, Sequence[str], None] = '21ca3d8248db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_locations_id'), 'fulfillment_locations', ['id'], unique=False)
    op.create_table('shipping_carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_shipping_carriers_id'), 'shipping_carriers', ['id'], unique=False)
    op.create_table('shipping_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_packages_id'), 'shipping_packages', ['id'], unique=False)
    op.create_table('shipping_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_profiles_id'), 'shipping_profiles', ['id'], unique=False)
    op.create_table('shipping_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_strategy', sa.Enum('closest_to_customer', 'primary_stock_first', name='routing_strategy'), nullable=False),
    sa.Column('allow_split_shipments', sa.Boolean(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('sender_city', sa.String(), nullable=True),
    sa.Column('sender_province', sa.String(), nullable=True),
    sa.Column('sender_country', sa.String(), nullable=True),
    sa.Column('sender_postal_code', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('packing_slip_show_sku', sa.Boolean(), nullable=False),
    sa.Column('packing_slip_show_variants', sa.Boolean(), nullable=False),
    sa.Column('packing_slip_show_quantity', sa.Boolean(), nullable=False),
    sa.Column('packing_slip_template', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['shipping_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_zones_id'), 'shipping_zones', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_zones_profile_id'), 'shipping_zones', ['profile_id'], unique=False)
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rate_type', sa.Enum('flat', 'price_based', 'weight_based', 'carrier', name='shipping_rate_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['shipping_carriers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['shipping_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rates_id'), 'shipping_rates', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_rates_zone_id'), 'shipping_rates', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipping_rates_zone_id'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_id'), table_name='shipping_rates')
    op.drop_table('shipping_rates')
    op.drop_index(op.f('ix_shipping_zones_profile_id'), table_name='shipping_zones')
    op.drop_index(op.f('ix_shipping_zones_id'), table_name='shipping_zones')
    op.drop_table('shipping_zones')
    op.drop_table('shipping_settings')
    op.drop_index(op.f('ix_shipping_profiles_id'), table_name='shipping_profiles')
    op.drop_table('shipping_profiles')
    op.drop_index(op.f('ix_shipping_packages_id'), table_name='shipping_packages')
    op.drop_table('shipping_packages')
    op.drop_index(op.f('ix_shipping_carriers_id'), table_name='shipping_carriers')
    op.drop_table('shipping_carriers')
    op.drop_index(op.f('ix_fulfillment_locations_id'), table_name='fulfillment_locations')
    op.drop_table('fulfillment_locations')
    # ### end Alembic commands ###
