"""add discount value columns

Revision ID: f0e1d2c3b4a5
Revises: a7e9f1c4d2b5
Create Date: 2026-08-28 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e1d2c3b4a5'
down_revision: Union[str, Sequence[str], None] = 'a7e9f1c4d2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('value', sa.Text(), nullable=True))
    op.add_column('discounts', sa.Column('percentage_value', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('discounts', sa.Column('value_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    op.drop_column('discounts', 'value_amount')
    op.drop_column('discounts', 'percentage_value')
    op.drop_column('discounts', 'value')
    # ### end Alembic commands ###