import type { Discount } from "./types"

export const MOCK_DISCOUNTS: Discount[] = [
  {
    id: 1,
    title: "VALENTINE15 - 15% Off Handcrafted Accessories",
    code: "VALENTINE15",
    status: "Active",
    method: "Code",
    eligibility: "All customers",
    type: "Percentage",
    value: "15% OFF",
    combinations: "Product discounts, Shipping discounts",
    used_count: 142,
    created_at: "Jan 25, 2026",
    start_date: "Jan 25, 2026",
    end_date: "Feb 15, 2026",
  },
  {
    id: 2,
    title: "FREE-SHIPPING-OVER-2000",
    code: "FREESHIP",
    status: "Active",
    method: "Automatic",
    eligibility: "All customers",
    type: "Free shipping",
    value: "Free Shipping",
    combinations: "Product discounts",
    used_count: 489,
    created_at: "Jan 1, 2026",
    start_date: "Jan 1, 2026",
  },
  {
    id: 3,
    title: "VIP-REPEATER-500 - Rs. 500 Off Next Order",
    code: "VIP500",
    status: "Active",
    method: "Code",
    eligibility: "Specific segments",
    type: "Fixed amount",
    value: "Rs. 500 OFF",
    combinations: "Shipping discounts",
    used_count: 64,
    created_at: "Jan 15, 2026",
    start_date: "Jan 15, 2026",
    end_date: "Mar 1, 2026",
  },
  {
    id: 4,
    title: "B2B-WHOLESALE-20",
    code: "B2B20",
    status: "Active",
    method: "Code",
    eligibility: "Specific customers",
    type: "Percentage",
    value: "20% OFF",
    combinations: "Can't combine with other discounts",
    used_count: 18,
    created_at: "Jan 10, 2026",
    start_date: "Jan 10, 2026",
  },
  {
    id: 5,
    title: "EID-SPECIAL-2025",
    code: "EID2025",
    status: "Expired",
    method: "Code",
    eligibility: "All customers",
    type: "Percentage",
    value: "20% OFF",
    combinations: "Product discounts",
    used_count: 312,
    created_at: "Apr 1, 2025",
    start_date: "Apr 1, 2025",
    end_date: "Apr 30, 2025",
  },
]

export async function listDiscounts(): Promise<Discount[]> {
  return MOCK_DISCOUNTS
}
