import type { Order, DraftOrder, AbandonedCheckout } from "./types"

export const MOCK_ORDERS: Order[] = [
  {
    id: 1022,
    order_number: "#1022",
    customer_id: 1,
    customer_name: "Muhammad Ali",
    customer_email: "m.ali@example.com",
    customer_phone: "+92 334 5399470",
    channel: "Online Store",
    currency: "PKR",
    subtotal: 1699,
    shipping_cost: 0,
    tax: 0,
    total: 1699,
    paid_amount: 1699,
    balance_due: 0,
    payment_status: "Paid",
    fulfillment_status: "Unfulfilled",
    delivery_status: "Processing",
    delivery_method: "Courier",
    tags: "VIP, High Value",
    destination: "Islamabad, Pakistan",
    shipping_address: "House 12, Street 4, F-8/3, Islamabad, Pakistan",
    billing_address: "House 12, Street 4, F-8/3, Islamabad, Pakistan",
    customer_note: "Please handle carefully, it is a gift for my father.",
    internal_note: "Verified Cash on Delivery / Card Payment.",
    tracking_company: "Leopards Courier",
    tracking_number: "LEO-9823412",
    is_archived: false,
    created_at: "Feb 8, 2026, 2:15 PM",
    items: [
      {
        id: 1,
        product_name: "ARDOR - Handmade Leather Card Holder Wallet",
        sku: "EL-WAL-001",
        variant_title: "Maroon / Genuine Leather",
        quantity: 1,
        unit_price: 1699,
        total_price: 1699,
        requires_shipping: true,
        is_gift_card: false,
      },
    ],
    notes: [
      {
        id: 1,
        order_id: 1022,
        author_name: "Bilal Hussain Abbasi",
        body: "Order verified via phone call. Ready for dispatch.",
        is_customer_visible: false,
        created_at: "Feb 8, 2026, 2:30 PM",
      },
    ],
    audit_logs: [
      {
        id: 1,
        order_id: 1022,
        event_type: "ORDER_CREATED",
        description: "Order placed online by customer Muhammad Ali.",
        actor_name: "Muhammad Ali",
        created_at: "Feb 8, 2026, 2:15 PM",
      },
      {
        id: 2,
        order_id: 1022,
        event_type: "PAYMENT_CONFIRMED",
        description: "Payment authorized (Rs. 1,699).",
        actor_name: "System Gateway",
        created_at: "Feb 8, 2026, 2:16 PM",
      },
    ],
  },
  {
    id: 1021,
    order_number: "#1021",
    customer_id: 2,
    customer_name: "Usman Tariq",
    customer_email: "usman.tariq@gmail.com",
    customer_phone: "+92 300 1234567",
    channel: "Online Store",
    currency: "PKR",
    subtotal: 2499,
    shipping_cost: 0,
    tax: 0,
    total: 2499,
    paid_amount: 2499,
    balance_due: 0,
    payment_status: "Paid",
    fulfillment_status: "Fulfilled",
    delivery_status: "Delivered",
    delivery_method: "Courier",
    tags: "Repeat Customer",
    destination: "Lahore, Pakistan",
    shipping_address: "45-C Model Town, Lahore, Pakistan",
    billing_address: "45-C Model Town, Lahore, Pakistan",
    tracking_company: "Sonic - Trax",
    tracking_number: "TRAX-8871239",
    is_archived: false,
    created_at: "Feb 8, 2026, 11:30 AM",
    items: [
      {
        id: 2,
        product_name: "SOVEREIGN - Real Leather Classic Dress Belt",
        sku: "EL-BELT-004",
        variant_title: "Dark Brown / Size 34",
        quantity: 1,
        unit_price: 2499,
        total_price: 2499,
        requires_shipping: true,
        is_gift_card: false,
      },
    ],
  },
  {
    id: 1020,
    order_number: "#1020",
    customer_id: 3,
    customer_name: "Hamza Sheikh",
    customer_email: "hamza.sheikh@hotmail.com",
    customer_phone: "+92 321 8899001",
    channel: "Online Store",
    currency: "PKR",
    subtotal: 2998,
    shipping_cost: 0,
    tax: 0,
    total: 2998,
    paid_amount: 0,
    balance_due: 2998,
    payment_status: "Pending",
    fulfillment_status: "Unfulfilled",
    delivery_status: "Processing",
    delivery_method: "Courier",
    tags: "COD",
    destination: "Rawalpindi, Pakistan",
    shipping_address: "Street 9, Satellite Town, Rawalpindi, Pakistan",
    billing_address: "Street 9, Satellite Town, Rawalpindi, Pakistan",
    is_archived: false,
    created_at: "Feb 7, 2026, 6:45 PM",
    items: [
      {
        id: 3,
        product_name: "HERALD - Handcrafted Leather Glasses Case",
        sku: "EL-CASE-003",
        variant_title: "Tan Leather",
        quantity: 2,
        unit_price: 1499,
        total_price: 2998,
        requires_shipping: true,
        is_gift_card: false,
      },
    ],
  },
  {
    id: 1019,
    order_number: "#1019",
    customer_id: 4,
    customer_name: "Ayesha Khan",
    customer_email: "ayesha.k@yahoo.com",
    customer_phone: "+92 312 4455667",
    channel: "Instagram Store",
    currency: "PKR",
    subtotal: 1399,
    shipping_cost: 0,
    tax: 0,
    total: 1399,
    paid_amount: 1399,
    balance_due: 0,
    payment_status: "Paid",
    fulfillment_status: "Fulfilled",
    delivery_status: "Delivered",
    delivery_method: "Courier",
    tags: "Social Order",
    destination: "Karachi, Pakistan",
    shipping_address: "Block 5, Clifton, Karachi, Pakistan",
    billing_address: "Block 5, Clifton, Karachi, Pakistan",
    tracking_company: "17TRACK",
    tracking_number: "17T-772183",
    is_archived: false,
    created_at: "Feb 7, 2026, 1:10 PM",
    items: [
      {
        id: 4,
        product_name: "MONARCH - Executive Leather Key Organizer",
        sku: "EL-KEY-002",
        variant_title: "Black Leather",
        quantity: 1,
        unit_price: 1399,
        total_price: 1399,
        requires_shipping: true,
        is_gift_card: false,
      },
    ],
  },
]

export async function listOrders(): Promise<Order[]> {
  return MOCK_ORDERS
}

export async function getOrder(orderId: number | string): Promise<Order | undefined> {
  return MOCK_ORDERS.find((o) => o.id.toString() === orderId.toString() || o.order_number === `#${orderId}`) || MOCK_ORDERS[0]
}
